In [6]:
import pandas as pd
data = {
    "A":[12,24,76889,34,234,1243],
    "B":[45,56,657,356,2135,2345],
    "c":[56658,87098,2134,234,000,0],
    "d":[00,234,0,234,134,0]
}

In [7]:
df=pd.DataFrame(data)

In [8]:
df

       A     B      c    d
0     12    45  56658    0
1     24    56  87098  234
2  76889   657   2134    0
3     34   356    234  234
4    234  2135      0  134
5   1243  2345      0    0

**MIN-MAX SCALER**

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
)
df_minmax

          A         B         c        d
0  0.000000  0.000000  0.650509  0.00000
1  0.000156  0.004783  1.000000  1.00000
2  1.000000  0.266087  0.024501  0.00000
3  0.000286  0.135217  0.002687  1.00000
4  0.002888  0.908696  0.000000  0.57265
5  0.016013  1.000000  0.000000  0.00000

**Z-SCORE NORMALIZATION**

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_standard = df.copy()
df_standard = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
)
df_standard

          A         B         c         d
0 -0.457582 -0.934871  0.929822 -0.948998
1 -0.457161 -0.923281  1.805992  1.264280
2  2.235811 -0.290084 -0.639569 -0.948998
3 -0.456811 -0.607209 -0.694258  1.264280
4 -0.449804  1.267098 -0.700993  0.318435
5 -0.414453  1.488348 -0.700993 -0.948998

**ROBUST-SCALER**

In [11]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
df_robust = df.copy()
df_robust = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
)
df_robust

           A         B         c         d
0  -0.126523 -0.282349  1.291039 -0.320574
1  -0.114078 -0.275619  1.999465  0.799043
2  79.600726  0.092077  0.022109 -0.320574
3  -0.103708 -0.092077 -0.022109  0.799043
4   0.103708  0.996329 -0.027555  0.320574
5   1.150117  1.124809 -0.027555 -0.320574